# Generated by Django 5.1.15 on 2026-09-03 23:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('order_system', 'Order system'), ('payment_gateway', 'Payment gateway'), ('bank_account', 'Bank account'), ('general_ledger', 'General ledger'), ('tax_system', 'Tax system')], max_length=32)),
                ('external_account_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_record_id', models.CharField(max_length=200)),
                ('record_type', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('fee', 'Fee'), ('tax', 'Tax'), ('refund', 'Refund'), ('settlement', 'Settlement'), ('bank_credit', 'Bank credit'), ('ledger_entry', 'Ledger entry')], max_length=32)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('occurred_at', models.DateTimeField()),
                ('content_hash', models.CharField(max_length=64)),
                ('raw_payload', models.JSONField(default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to='reconciliation.financialdatasource')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='financialdatasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data_sources', to='reconciliation.organization'),
        ),
        migrations.CreateModel(
            name='ReconciliationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('case_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('needs_review', 'Needs review'), ('insufficient_evidence', 'Insufficient evidence')], default='open', max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('expected_amount_minor', models.BigIntegerField()),
                ('actual_amount_minor', models.BigIntegerField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_break_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_break_cases', to='reconciliation.financialrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_cases', to='reconciliation.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveSmallIntegerField()),
                ('match_method', models.CharField(choices=[('exact_reference', 'Exact reference'), ('source_reference', 'Source reference'), ('amount_and_time', 'Amount and time'), ('manual_review', 'Manual review')], max_length=32)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('matching_reason', models.CharField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_evidence_connections', to='reconciliation.financialrecord')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_evidence_connections', to='reconciliation.financialrecord')),
                ('reconciliation_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_connections', to='reconciliation.reconciliationcase')),
            ],
            options={
                'ordering': ['sequence_number', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialrecord',
            constraint=models.UniqueConstraint(fields=('source', 'external_record_id', 'content_hash'), name='unique_financial_record_version'),
        ),
        migrations.AddConstraint(
            model_name='financialdatasource',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_data_source_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationcase',
            constraint=models.UniqueConstraint(fields=('organization', 'case_reference'), name='unique_case_reference_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='evidenceconnection',
            constraint=models.CheckConstraint(condition=models.Q(('source_record', models.F('destination_record')), _negated=True), name='evidence_connection_cannot_link_record_to_itself'),
        ),
        migrations.AddConstraint(
            model_name='evidenceconnection',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='evidence_confidence_between_zero_and_one'),
        ),
        migrations.AddConstraint(
            model_name='evidenceconnection',
            constraint=models.UniqueConstraint(fields=('reconciliation_case', 'sequence_number'), name='unique_evidence_sequence_per_case'),
        ),
    ]
