# Generated by Django 5.1.15 on 2026-09-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('tool_calls', models.JSONField(default=list)),
                ('conclusion', models.TextField()),
                ('recommended_action', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('evidence_cited', models.JSONField(default=list)),
                ('sufficient_evidence', models.BooleanField()),
                ('model_version', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=120)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('waiting', 'Waiting')], max_length=12)),
                ('evidence', models.JSONField(default=list)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('ran_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='financialrecord',
            name='unique_financial_record_version',
        ),
        migrations.AddField(
            model_name='evidenceconnection',
            name='created_by',
            field=models.CharField(choices=[('rules_engine', 'Rules engine'), ('human', 'Human')], default='rules_engine', max_length=20),
        ),
        migrations.AddField(
            model_name='evidenceconnection',
            name='link_type',
            field=models.CharField(default='transaction_flow', max_length=50),
        ),
        migrations.AddField(
            model_name='evidenceconnection',
            name='rationale',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='entity_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='fee_minor',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='tax_minor',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationcase',
            name='entity_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reconciliationcase',
            name='exception_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reconciliationcase',
            name='owner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reconciliationcase',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='financialrecord',
            constraint=models.UniqueConstraint(fields=('source', 'record_type', 'external_record_id'), name='unique_financial_source_record'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='reconciliation_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='reconciliation.reconciliationcase'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='reconciliation_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='reconciliation.reconciliationcase'),
        ),
        migrations.AddConstraint(
            model_name='checkresult',
            constraint=models.UniqueConstraint(fields=('reconciliation_case', 'check_name'), name='unique_check_name_per_case'),
        ),
    ]
