# Generated by Django 5.1.15 on 2026-09-04 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_agentrun_checkresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_reference', models.CharField(max_length=100)),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('processed', 'Processed'), ('partial', 'Partially processed'), ('rejected', 'Rejected')], default='processing', max_length=16)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_batches', to='reconciliation.financialdatasource')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('source', 'batch_reference'), name='unique_ingestion_batch_per_source')],
            },
        ),
    ]
