# Generated by Django 5.1.15 on 2026-09-05 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_ingestionbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='fallback_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='prompt_version',
            field=models.CharField(default='investigation-v2', max_length=40),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='normalization_version',
            field=models.CharField(default='canonical-v1', max_length=40),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='normalized_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reconciliationcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationcase',
            name='workflow_status',
            field=models.CharField(default='unassigned', max_length=32),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reconciliation.organization')),
                ('reconciliation_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reconciliation.reconciliationcase')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IngestionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_reference', models.CharField(max_length=100)),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('outcome', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reconciliation.financialdatasource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('as_of', models.DateTimeField()),
                ('engine_version', models.CharField(default='control-v2', max_length=40)),
                ('inputs', models.JSONField()),
                ('rules', models.JSONField()),
                ('decisions', models.JSONField()),
                ('checks', models.JSONField()),
                ('result', models.JSONField()),
                ('source_watermarks', models.JSONField()),
                ('input_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciliation_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='reconciliation.reconciliationcase')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='reconciliation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reconciliation.reconciliationrun'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('analyst', 'Analyst'), ('manager', 'Manager'), ('administrator', 'Administrator'), ('auditor', 'Auditor')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconciliation.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_membership')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('fee_basis_points', models.PositiveIntegerField()),
                ('tax_basis_points', models.PositiveIntegerField()),
                ('refund_policy', models.CharField(choices=[('deduct_processed', 'Deduct processed refunds'), ('external', 'Refunds settled separately')], default='deduct_processed', max_length=32)),
                ('bank_wait_hours', models.PositiveIntegerField(default=48)),
                ('settlement_wait_hours', models.PositiveIntegerField(default=48)),
                ('tolerance_minor', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_versions', to='reconciliation.financialdatasource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'version'), name='unique_source_rule_version')],
            },
        ),
    ]
