# Generated by Django 5.2.17 on 2026-09-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0006_preserve_legacy_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='latency_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='model_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
